version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 3000:3000
    user: '104'
  volumes:
      - ./postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
volumes:
  grafana:
    driver: local

